---
- name: Enable the RabbitMQ Management Console
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq-server

- name: Ensure that the RabbitMQ service is running
  service: name=rabbitmq-server state=started enabled=yes